{% set version = "0.7.0.dev2" %}

package:
  name: ecole
  version: {{ version }}

source:
  url: https://github.com/ds4dm/ecole/archive/v{{ version }}.tar.gz
  sha256: 6c5559a1dd0144981379ae212c2b380ca62034e53a9b6faf57d48842d018838d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.15
    - ninja
  host:
    - scip
    - fmt
    - xtensor
    - xsimd
    - python
    - pip
    - scikit-build
    - pybind11
    - numpy >=1.11
    - xtensor-python
  run:
    - python
    - numpy
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
  run_constrained:
    - pyscipopt >=3.0.1

test:
  imports:
    - ecole
    - ecole.reward
    - ecole.environment
  source_files:
    - libecole/tests/data/
    - python/tests
  requires:
    - pytest
    - pytest-helpers-namespace
    - pyscipopt
  commands:
    - python -m pytest --no-slow python/tests

about:
  home: https://www.ecole.ai/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Extensible Combinatorial Optimization Learning Environments
  doc_url: https://doc.ecole.ai/

extra:
  recipe-maintainers:
    - AntoinePrv
    - gasse
